name: ShopEasy CI

on:
  push:
    branches: [ docker-aws-practice ]
  pull_request:
    branches: [ docker-aws-practice ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 20 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 의존성 설치
        run: npm install

      - name: 테스트 실행
        run: npm test

      - name: 빌드 확인
        run: echo "빌드 성공!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AWS 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role